apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap 
  labels:
    app: ldap 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap 
  template:
    metadata:
      labels:
        app: ldap 
    spec:
      containers:
      - name: ldap 
        image: osixia/openldap 
        args: ["--loglevel", "debug"]
        env:
        - name: "LDAP_SEED_INTERNAL_LDIF_PATH"
          value: "/import"
        ports:
        - containerPort: 389 
        volumeMounts:
        - name: import
          mountPath: "/import"
      enableServiceLinks: false
      volumes:
      - name: import 
        configMap:
          name: ldif 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldap 
  labels:
    app: phpldap 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldap 
  template:
    metadata:
      labels:
        app: phpldap 
    spec:
      containers:
      - name: phpldap 
        image: osixia/phpldapadmin
        ports:
        - containerPort: 443 
        env:
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: ldap
