images:
- name: osixia/openldap
  newTag: 1.5.0
- name: osixia/phpldapadmin
  newTag: 0.9.0 

namespace: ldap

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: ldif
  files:
  - ldap.ldif
