apiVersion: v1
kind: Service
metadata:
  name: ldap 
spec:
  selector: 
    app: ldap
  ports:
    - protocol: TCP
      port: 389 
      targetPort: 389 
---
apiVersion: v1
kind: Service
metadata:
  name: phpldap 
spec:
  type: LoadBalancer
  selector: 
    app: phpldap
  ports:
    - protocol: TCP
      port: 8443 
      targetPort: 443 
